# Generated by Django 4.2.6 on 2023-11-08 13:22

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=255, verbose_name='Заголовок статьи')),
                ('descriptions_news', models.TextField(verbose_name='Описание статьи')),
                ('image_news', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image_news/')),
                ('create_news', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания статьи')),
            ],
            options={
                'verbose_name': 'Добавить статью',
                'verbose_name_plural': 'Добавить статьи',
            },
        ),
    ]
