# Generated by Django 4.2.6 on 2023-11-08 19:52

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='create_news',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='descriptions_news',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_news',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_news',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/'),
            preserve_default=False,
        ),
    ]
