# Generated by Django 4.2.6 on 2023-11-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_create_news_news_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
