# Generated by Django 4.2.6 on 2023-11-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='descriptions',
            field=models.TextField(verbose_name='Описание новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок новости'),
        ),
    ]
