# Generated by Django 4.2.6 on 2023-11-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_about_satisfied_remove_about_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
