# Generated by Django 4.2.6 on 2023-11-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='process', verbose_name='фото')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('descriptions', models.CharField(max_length=300, verbose_name='Описание')),
                ('number', models.CharField(max_length=100, verbose_name='Номер Блога')),
                ('icon', models.CharField(choices=[('ИЗУЧЕНИЕ', 'ИЗУЧЕНИЕ'), ('РАЗРАБОТКА', 'РАЗРАБОТКА'), ('ЗАПУСК', 'ЗАПУСК')], max_length=50, verbose_name='Выберите Иконку')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Процесс работы',
            },
        ),
        migrations.DeleteModel(
            name='Faqs',
        ),
        migrations.RemoveField(
            model_name='price',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
