# Generated by Django 4.2.6 on 2023-11-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_about_descriptions_2_about_image_2_about_title_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=155, null=True, verbose_name='Выбор услуги')),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Имя пользователя')),
                ('phone', models.CharField(blank=True, max_length=155, null=True, verbose_name='Номер телефона')),
                ('email', models.URLField(blank=True, max_length=155, null=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Оставленная заявка на услугу',
                'verbose_name_plural': 'Оставленная заявка на услугу',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Номер телефона'),
        ),
    ]
