# Generated by Django 4.2.6 on 2023-11-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_service_contact_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationprocess',
            name='number',
        ),
    ]
