# Generated by Django 4.2.6 on 2023-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_operationprocess_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationprocess',
            name='title',
            field=models.TextField(verbose_name='Заголовка'),
        ),
    ]
