# Generated by Django 4.2.6 on 2023-11-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_operationprocess_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='telegram',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона (whatsapp)'),
        ),
    ]
