# Generated by Django 4.2.6 on 2023-11-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_settings_telegram_alter_settings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='telegram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ),
    ]
