# Generated by Django 4.2.6 on 2023-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_settings_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='whatsapp',
            field=models.CharField(default=1, max_length=255, verbose_name='Whatsapp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
    ]
