# Generated by Django 4.2.6 on 2023-11-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_settings_whatsapp_alter_settings_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='whatsapp',
        ),
    ]
