# Generated by Django 4.2.6 on 2023-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id_team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone_doctor',
        ),
        migrations.AddField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='team',
            name='skype',
            field=models.URLField(blank=True, null=True, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
