# Generated by Django 4.2.6 on 2023-11-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team_id_team_remove_team_phone_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Doctor',
        ),
    ]
