# Generated by Django 4.2.6 on 2023-11-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_delete_contact_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='descriptions',
            field=models.TextField(max_length=255, verbose_name='О участнике команды'),
        ),
    ]
