# Generated by Django 4.2.6 on 2023-11-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='phone',
        ),
        migrations.AddField(
            model_name='team',
            name='descriptions_1',
            field=models.TextField(default=1, max_length=255, verbose_name="Описание в основной странице 'Наша команда'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='descriptions_2',
            field=models.TextField(default=1, max_length=255, verbose_name="Описание на странице 'Детальный просмотр команды'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='title_1',
            field=models.CharField(default=1, max_length=255, verbose_name="Заголовок в основной странице 'Наша команда'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='title_2',
            field=models.CharField(default=1, max_length=255, verbose_name="Заголовок на странице 'Детальный просмотр команды'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube - ссылка на видео (О команде)'),
        ),
    ]
