# Generated by Django 4.2.6 on 2023-11-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_remove_team_phone_team_descriptions_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='descriptions_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='descriptions_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='youtube',
        ),
    ]
