# Generated by Django 4.2.6 on 2023-11-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущество'},
        ),
    ]
